# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for NPM packages
  - package-ecosystem: "npm"
    directory: "/docs"
    target-branch: "docs"
    schedule:
      interval: "daily"
